///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trend_Task
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording6 recording.
    /// </summary>
    [TestModule("598235ea-a9cc-4bc3-b4b4-944a95615fc0", ModuleType.Recording, 1)]
    public partial class Recording6 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Trend_TaskRepository repository.
        /// </summary>
        public static Trend_TaskRepository repo = Trend_TaskRepository.Instance;

        static Recording6 instance = new Recording6();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording6()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording6 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Sepetim' at 35;11.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.SepetimInfo, new RecordItemIndex(0));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Sepetim.Click("35;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.SepetiOnayla' at 68;20.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.SepetiOnaylaInfo, new RecordItemIndex(1));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.SepetiOnayla.Click("68;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxText' at 12;6.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxTextInfo, new RecordItemIndex(2));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxText.Click("12;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxText' at 12;6.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxTextInfo, new RecordItemIndex(3));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxText.Click("12;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxText' at 14;5.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxTextInfo, new RecordItemIndex(4));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.PCheckboxText.Click("14;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.KaydetVeDevamEt' at 136;14.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.KaydetVeDevamEtInfo, new RecordItemIndex(5));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.KaydetVeDevamEt.Click("136;14");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
